# Logo (Font Awesome Class)
fa_logo: fa-cube

# Header
menu:
  主页: /
  档案: /archives
  个人网页: /about/index.html
  # Tags: /tags
  分类: /categories
  #Contact: /contact.html

# Default post title
default_post_title: Untitled

# Archive Date Format
archive_date_format: MMM YYYY

# Comments.
comments:
  # Disqus comments
  disqus_shortname:

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/?lang=en
facebook_url: https://www.facebook.com/
github_url: https://github.com/xiexuliunian
email_url: zzuzxd@126.com

# Footer About Text
footer_about: "欢迎您能来到我的GitHub博客主页:<a href=\"https://github.com/xiexuliunian\">zxd</a>."

# Footer Copyright Line
footer_copyright: "zxd. All right reserved | Design & Hexo <a href=\"http://www.codeblocq.com/\">YF</a>"

